name: Ping Render Health

on:
  schedule:
    # Every 5 minutes
    - cron:  '*/5 * * * *'
  workflow_dispatch:    # allows manual run from the Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl health endpoint
        run: |
          echo "Pinging ${{ secrets.HEALTH_URL }} — should return OK"
          curl --fail --silent --show-error "${{ secrets.HEALTH_URL }}" \
            || (echo "Health check failed" && exit 1)
